Revert "ANDROID: sched: Export set_next_entity"
This reverts commit f94f1b91143ed44a6c64a6d201cd3b41e3c90863.

Commit 0fcb70851fbfe ("Makefile.extrawarn: turn on missing-prototypes
globally") enabled warnings for all missing prototypes which causes
errors due to the fact that we have -Werror enabled.

  kernel/sched/fair.c:5442:6:
    error: no previous prototype for 'set_next_entity' [-Werror=missing-prototypes]

Let's strip these out.  If anyone is still using them, they can reapply
them properly, complete with prototypes.

Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: If52e669c1f20b428fb75dd88f4f8522df07e7af0