ANDROID: usb: gadget: f_midi: Add missing stub for android_clear_midi_device_info()
When building without CONFIG_ANDROID_USB_F_MIDI_INFO, such as ARCH=arm
defconfig, an error occurs due to a missing stub for
android_clear_midi_device_info():

  drivers/usb/gadget/function/f_midi.c:796:3: error: call to undeclared function 'android_clear_midi_device_info'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    796 |                 android_clear_midi_device_info(&opts->android_midi_info);
        |                 ^
  drivers/usb/gadget/function/f_midi.c:796:3: note: did you mean 'android_set_midi_device_info'?
  drivers/usb/gadget/function/android_f_midi_info.h:95:19: note: 'android_set_midi_device_info' declared here
     95 | static inline int android_set_midi_device_info(struct f_midi_info *ctx,
        |                   ^
  drivers/usb/gadget/function/f_midi.c:1315:2: error: call to undeclared function 'android_clear_midi_device_info'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
   1315 |         android_clear_midi_device_info(&opts->android_midi_info);
        |         ^
  2 errors generated.

Add the missing stub to fix the build.

Change-Id: I6413197f69599241862ea1607b7cd4fcb384591a
Fixes: 53eddc82c203 ("ANDROID: usb: gadget: f_midi: rework cleanup path")
Signed-off-by: Nathan Chancellor <nathan@kernel.org>