Revert "clocksource/drivers/mxs_timer: Add missing semicolon when DEBUG is defined"
This reverts commit 88c0859600c28389241f4cf3e36c5d016b885650.

This unnecessary patch causes the following error:

 drivers/clocksource/mxs_timer.c:173:3: error: ‘clock_event_mode_label’ undeclared
       (first use in this function); did you mean ‘clock_event_mode’?

Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: I68ecc357156ad7aa6b3175bc21f5c62552862e0a