ANDROID: Fix the CONFIG_BLK_DEV_ZONED=n build
Fix the following arm64 defconfig build error:

drivers/scsi/sd.c:1308:6: error: implicit declaration of function 'blk_rq_is_seq_zone_write' [-Werror,-Wimplicit-function-declaration]
            blk_rq_is_seq_zone_write(rq))
            ^
1 error generated.

Bug: 4714656
Fixes: 33aea9741e00 ("ANDROID: scsi: Retry unaligned zoned writes")
Reported-by: willdeacon@google.com
Change-Id: Ibd3b85395dd376fd8664481693895e301b8658a1
Signed-off-by: Bart Van Assche <bvanassche@google.com>