Revert "UPSTREAM: binder: Fix race between mmap() and binder_alloc_print_pages()"
This reverts commit eb533cbd7de397d538a619f86c1828d75e08d3ec.

Reverting due to build errors:

 drivers/staging/android/binder_alloc.c:852:6: error: implicit declaration of function 'binder_alloc_get_vma'; did you mean 'binder_alloc_new_buf'? [-Werror=implicit-function-declaration]
  852 |  if (binder_alloc_get_vma(alloc) != NULL) {
      |      ^~~~~~~~~~~~~~~~~~~~
      |      binder_alloc_new_buf
 drivers/staging/android/binder_alloc.c:852:34: warning: comparison between pointer and integer
  852 |  if (binder_alloc_get_vma(alloc) != NULL) {
      |                                  ^~

Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: Ic8636f4218bb30d74628a039ea4cef5dafe93452