ANDROID: Revert "neighbour: fix neigh_dump_info() return value"
This reverts commit 7e4975f7e7fb0eba3cbb69d9c467750a1c3ce131. This
change causes the vts_kernel_net_tests to fail.

Run via:
  /...aosp-tests.../net/test/run_net_test.sh --builder neighbour_test.py
fails with:
  TypeError: NLMsgHdr requires a bytes object of length 16, got 4

Test: run vts -m vts_kernel_net_tests
Bug: 356680538
Change-Id: I1d5b5fe0bf2263847d3990154cc4cb7ca3132602
Signed-off-by: Will McVicker <willmcvicker@google.com>