Revert "ANDROID: GKI: vendor code needs __balance_callbacks access"
This reverts commit 51ba045c81b3d00225cfe6866e5fd18a1faddf30.

Commit 0fcb70851fbfe ("Makefile.extrawarn: turn on missing-prototypes
globally") enabled warnings for all missing prototypes which causes
errors due to the fact that we have -Werror enabled.

Consequently, we now have build errors all of the place.

  kernel/sched/core.c:5172:6:
    error: no previous prototype for function '__balance_callbacks' [-Werror,-Wmissing-prototypes]

Let's strip these out.  If anyone is still using them, they can reapply
them properly, complete with prototypes.

Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I9e67601b02a1c86e6f8ba7e3fc71d5132fad83bd