ANDROID: GKI: gki_module: Provide namespacing for cmp_name()
There are more than one functions called cmp_name() and at least one of
them is exported.  Let's namespace this one to avoid any confusion or
collisions.

  kernel/module/gki_module.c:27:12: error: static declaration of 'cmp_name' follows non-static declaration
     27 | static int cmp_name(const void *sym, const void *protected_sym)
        |            ^
  kernel/module/internal.h:109:5: note: previous declaration is here
    109 | int cmp_name(const void *name, const void *sym);
        |     ^

Fixes: e9669eeb2f45 ("ANDROID: GKI: Add module load time symbol protection")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I8f85c6b9546ab1547f8a5200919888249c9d7592