FROMLIST: arm64: link with -z norelro regardless of CONFIG_RELOCATABLE
With CONFIG_EXPERT=y, CONFIG_KASAN=y, CONFIG_RANDOMIZE_BASE=n,
CONFIG_RELOCATABLE=n, we observe the following failure when trying to
link the kernel image with LD=ld.lld:

error: section: .exit.data is not contiguous with other relro sections

ld.lld defaults to -z relro while ld.bfd defaults to -z norelro. This
was previously fixed, but only for CONFIG_RELOCATABLE=y.

Cc: stable@vger.kernel.org
Fixes: commit 3bbd3db86470 ("arm64: relocatable: fix inconsistencies in linker script and options")
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>

Bug: 170775238
Link: https://lore.kernel.org/lkml/20201016175339.2429280-1-ndesaulniers@google.com/T/
Change-Id: Id6028d56b936008eb2972092a3c9ce6c35296545
Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>