ANDROID: ABI: remove stale symbol
The following symbol no longer exists after reverting an out-of-tree
typec contaminant patch in favor of its upstream version:

 - tcpm_is_debouncing

Removing the symbol fixes the following KMI build issue:

  ERROR: Checking for kmi_symbol_list_strict_mode
  [...]
  Symbols missing from the ksymtab:
    tcpm_is_debouncing

Bug: 273751441
Change-Id: I0f842e61237187c54dc471567c2b6df455778548
Signed-off-by: Carlos Llamas <cmllamas@google.com>