ANDROID: add forward declaration vm_unmapped_area_info
aosp/2215503 remove inclusions from hook definition headers
and build breakage detected on pixel device.

include/trace/hooks/mm.h:80:40: error: declaration of 'struct vm_unmapped_area_info' will not be visible outside of this function

Fix this by adding struct vm_unmapped_area_info forward declaration.

Fixes: 7108d9d0e5f2 ("ANDROID: remove inclusions from hook definition headers")
Bug: 233047575
Signed-off-by: Robin Peng <robinpeng@google.com>
Change-Id: I8989ba78977a26e13c79f9efb156bf8317c1010e