ANDROID: tracepoint: Include header containing prototype for android_rvh_probe_register()
Without it, some builds rightly complain:

  kernel/tracepoint.c:840:5:
    error: no previous prototype for 'android_rvh_probe_register' [-Werror=missing-prototypes]
      int android_rvh_probe_register(struct tracepoint *tp, void *probe, void *data)
          ^~~~~~~~~~~~~~~~~~~~~~~~~~

Fixes: e0cfc5fd8c93 ("ANDROID: vendor_hooks: Allow multiple attachments to restricted hooks")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Ib23a9d5cf50aadb59db85d3f4e9b4cca05f93643