ANDROID: arm64: fix allmodconfig break in arch/arm64/mm/context.c
In the 4.4.197 merge, the 'bool sign' argument was added to
cpuid_feature_extract_field_width(), but not changed
in arch/arm64/mm/context.c. This resulted in a kernelci
build-break for allmodconfig builds:

arch/arm64/mm/context.c:213:12: error: too few arguments to
function 'cpuid_feature_extract_field'

Change-Id: Ie27b93ae76e50e3e9b620402193eb13bf593dd2b
Fixes: 9e6c61d150319 ("Merge 4.4.197 into android-4.4-o")
Signed-off-by: Todd Kjos <tkjos@google.com>