ANDROID: GKI: gki_module: Include internal.h in order to pick-up exported prototypes
Fixes new -Wmissing-prototypes warnings (errors due to -Werror) like these:

  kernel/module/gki_module.c:35:6:
    error: no previous prototype for function 'gki_is_module_protected_export' [-Werror,-Wmissing-prototypes]
       35 | bool gki_is_module_protected_export(const char *name)
          |      ^
  kernel/module/gki_module.c:55:6:
    error: no previous prototype for function 'gki_is_module_unprotected_symbol' [-Werror,-Wmissing-prototypes]
     55 | bool gki_is_module_unprotected_symbol(const char *name)
        |      ^

Fixes: e9669eeb2f45 ("ANDROID: GKI: Add module load time symbol protection")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: I804f149e63db75650bb4bf1d9e77ce382eb36f70