ANDROID: mm: omm: Provide prototype for exported dump_tasks()
Commit 0fcb70851fbfe ("Makefile.extrawarn: turn on missing-prototypes
globally") enabled warnings for all missing prototypes which causes
errors due to the fact that we have -Werror enabled.

Provide missing prototype for exported dump_tasks() function in
order to avoid the following build errors:

  mm/oom_kill.c:424:6:
    error: no previous prototype for 'dump_tasks' [-Werror=missing-prototypes]

Fixes: 4df28ddcd988 ("ANDROID: mm: export dump_tasks symbol.")
Signed-off-by: Lee Jones <joneslee@google.com>
Change-Id: Ifb6e4997cef108c8b037ce6530c7b9beedb24b7b